### ISSUE TITLE
Variables to track campaign events

### ISSUE THREAD

**Issue by cooljeanius** [Ashmyr/DwarvishKingdom#28]
Specifically, the following things could be represented by variables:
- [x] Whether you read the book
- [x] Whether the drakes are your allies (if Ka'reius survived)
- [x] If the trolls are your allies (i.e. if Garug survived with you until S04)

Anything else?

**Comment by Ashmyr** [comment]
I've managed to set up the book variable after some coding. I assume the next two should be simple.

**Comment by Ashmyr** [comment]
Done, I think, though you can review it later.

**Comment by Ashmyr** [comment]
complete

**Comment by cooljeanius** [comment]
> complete

...in which commit? I can't seem to find it...
