### ISSUE TITLE
Dialogue edits for clarity and brevity

### ISSUE THREAD

**Issue by cooljeanius** [Ashmyr/DwarvishKingdom#29]
Some of the text can be a bit verbose at times; I can give the dialogue a copyedit if you'd like me to (and if I don't realize I have other things I ought to be doing instead)

**Comment by Ashmyr** [comment]
If you want, you can attempt so, yes. Let me know when. Just don't reduce it too much.

**Comment by Ashmyr** [comment]
I'll wait for your advice before doing anything. Do keep in mind the themes I want to focus on, though, and I don't want too much edited away.

**Comment by cooljeanius** [comment]
Never mind
