### ISSUE TITLE
Right-click menus for extra journal entries?

### ISSUE THREAD

**Issue by cooljeanius** [Ashmyr/DwarvishKingdom#30]
idk what this one means; just reproducing it here for posterity

**Comment by Ashmyr** [comment]
Oh, so the player gets extra journal entries for extra things they did. These come in the form of narrator bits rather than story. There's 1 in S2, 1 in S3, and 2 in S4. Someone suggested making them right-click menus so the player doesn't have to do so much reading.

**Comment by cooljeanius** [comment]
Never mind
