### ISSUE TITLE
Consider renaming existing scenarios

### ISSUE THREAD

**Issue by cooljeanius** [Ashmyr/DwarvishKingdom#32]
e.g. "Burial Chamber" to "Sanctity of the Dead" or something

**Comment by Ashmyr** [comment]
I renamed Burial Chamber. Might rename more.

**Comment by Ashmyr** [comment]
I think I'll leave it for now, but consider it in the future.

**Comment by cooljeanius** [comment]
Note that renaming scenarios can break saves, so it's something to be careful about after this campaign has reached 1.0
