### ISSUE TITLE
Fix Dwarvish Mage's description and sprites

### ISSUE THREAD

**Issue by cooljeanius** [Ashmyr/DwarvishKingdom#33]
Also I'd rename its `.cfg` file too while you're at it; `Mage.cfg` is ambiguous with the human one. Also maybe reorganize unit files to use subdirectories to group similar units together?

**Comment by Ashmyr** [comment]
I could do that, but wouldn't I need to specify the subdirectories in main.cfg?

**Comment by cooljeanius** [comment]
> I could do that, but wouldn't I need to specify the subdirectories in main.cfg?

Yeah, or something like that... indecision about how to actually do so is why I haven't gotten around to doing the similar cooljeanius/The_War_of_Terrador#9 yet, btw...

**Comment by cooljeanius** [comment]
Never mind
