### ISSUE TITLE
Bonuses for loyal units

### ISSUE THREAD

**Issue by cooljeanius** [Ashmyr/DwarvishKingdom#34]
Apparently there might already be some bonuses for loyal units that just need to be made more clear? I think the macro to recall loyal units at the start of scenarios might also fit here...

**Comment by Ashmyr** [comment]
Yeah, maybe one of the drakes could have {STEADFAST}? It'd only help against blade, impact and fire tho.

**Comment by Ashmyr** [comment]
I gave the glider STEADFAST, and implemented {RECALL_ALL_LOYALS}.

**Comment by cooljeanius** [comment]
> I gave the glider STEADFAST, and implemented {RECALL_ALL_LOYALS}.

...in which commit?
