### ISSUE TITLE
Death messages for more units

### ISSUE THREAD

**Issue by cooljeanius** [Ashmyr/DwarvishKingdom#35]
Specifically:
~~- [ ] Revenant~~
- [x] Bandit
- [x] both loyal drakes
- [x] make Arolmar's more unique
- [x] Blackrock leaders(?)

**Comment by Ashmyr** [comment]
I'll figure this one out. Specifically there's 3 Blackrock leaders, 1 in Tunnels of Flame and 2 in Troll Domain.

**Comment by Ashmyr** [comment]
I'm going to skip the Revenant for now because it's hard to think of a death message that works for either the Outlaws killing him or Arolmar.

**Comment by cooljeanius** [comment]
note that if you include the issue number in your commit message along with the words "closes", GitHub will auto-close the issue for you
