### ISSUE TITLE
Use more of the map in S02, "Feral Tunnels"

### ISSUE THREAD

**Issue by cooljeanius** [Ashmyr/DwarvishKingdom#36]
The map for S02 is currently a lot bigger than it needs to be; a lot of that extra space could be used by stashing more easter eggs down secret passages that the player might not necessarily notice or something (e.g. the river, if you follow it all the way to the east)

**Comment by Ashmyr** [comment]
I'll see what can be done.

**Comment by Ashmyr** [comment]
I've added a ring of speed. I think the rest is fine.

**Comment by cooljeanius** [comment]
> I've added a ring of speed. I think the rest is fine.

Where?
